export const inputCustomer = [
    {
        name: "customerName",
        label: "ชื่อ",
        type: "text",
        placeholder: "a",
        width: "3/12",
        value: "",
        requied: true,
    },
    {
        name: "address",
        label: "ที่อยู่",
        type: "text",
        placeholder: "a",
        width: "6/12",
        value: "",
        requied: true,
    },
    {
        name: "idCardNumber",
        label: "เลขประจำตัวประชาชน",
        type: "text",
        placeholder: "a",
        width: "3/12",
        value: "",
        requied: true,
    },
    {
        name: "phoneNumber",
        label: "เบอร์ติดต่อ",
        type: "text",
        placeholder: "a",
        width: "3/12",
        value: "",
        requied: true,
    },
    {
        name: "downPayment",
        label: "เงินดาวน์",
        type: "text",
        placeholder: "a",
        width: "3/12",
        value: "",
        requied: true,
    },
    {
        name: "totalOrder",
        label: "ยอดจัด",
        type: "text",
        placeholder: "a",
        width: "3/12",
        value: "",
        requied: true,
    },
    {
        name: "saleType",
        label: "การซื้อ",
        type: "text",
        placeholder: "a",
        width: "3/12",
        value: "",
        requied: true,
    },
    {
        name: "numInstallments",
        label: "จำนวนงวด",
        type: "text",
        placeholder: "a",
        width: "3/12",
        value: "",
        requied: true,
    },
    {
        name: "interestRate",
        label: "อัตราดอกเบี้ย",
        type: "text",
        placeholder: "a",
        width: "3/12",
        value: "",
        requied: true,
    },
    // ------------------------------------------------------- //
    // {
    //     name: "f",
    //     label: "ราคาที่ต้องการ",
    //     type: "text",
    //     placeholder: "a",
    //     width: "3/12",
    //     value: "",
    //     requied: true,
    // },
    // ------------------------------------------------------- //
    {
        name: "interestType",
        label: "การชำระดอกเบี้ย",
        type: "text",
        placeholder: "a",
        width: "3/12",
        value: "",
        requied: true,
    },
    {
        name: "interestMonth",
        label: "ดอกเบี้ย/เดือน",
        type: "text",
        placeholder: "a",
        width: "3/12",
        value: "",
        requied: true,
    },
    {
        name: "discount",
        label: "ส่วนลด",
        type: "text",
        placeholder: "a",
        width: "3/12",
        value: "",
        requied: true,
    },
    {
        name: "gps",
        label: "GPS",
        type: "text",
        placeholder: "a",
        width: "3/12",
        value: "",
        requied: true,
    },

]