export const inputCustomer = [
    {
        name: "a",
        label: "ชื่อ",
        type: "text",
        placeholder: "a",
        width: "3/12",
        value: "",
    },
    {
        name: "b",
        label: "ที่อยู่",
        type: "text",
        placeholder: "a",
        width: "6/12",
        value: "",
    },
    {
        name: "c",
        label: "เลขประจำตัวประชาชน",
        type: "text",
        placeholder: "a",
        width: "3/12",
        value: "",
    },
    {
        name: "d",
        label: "เบอร์ติดต่อ",
        type: "text",
        placeholder: "a",
        width: "3/12",
        value: "",
    },
    {
        name: "e",
        label: "เงินดาวน์",
        type: "text",
        placeholder: "a",
        width: "3/12",
        value: "",
    },
    {
        name: "f",
        label: "ยอดจัด",
        type: "text",
        placeholder: "a",
        width: "3/12",
        value: "",
    },
    {
        name: "g",
        label: "การซื้อ",
        type: "text",
        placeholder: "a",
        width: "3/12",
        value: "",
    },
    {
        name: "g",
        label: "จำนวนงวด",
        type: "text",
        placeholder: "a",
        width: "3/12",
        value: "",
    },
    {
        name: "i",
        label: "อัตราดอกเบี้ย",
        type: "text",
        placeholder: "a",
        width: "3/12",
        value: "",
    },
    {
        name: "j",
        label: "การชำระดอกเบี้ย",
        type: "text",
        placeholder: "a",
        width: "3/12",
        value: "",
    },
    {
        name: "k",
        label: "ดอกเบี้ย/เดือน",
        type: "text",
        placeholder: "a",
        width: "3/12",
        value: "",
    },
    {
        name: "l",
        label: "ส่วนลด",
        type: "text",
        placeholder: "a",
        width: "3/12",
        value: "",
    },
    {
        name: "j",
        label: "GPS",
        type: "text",
        placeholder: "a",
        width: "3/12",
        value: "",
    },
    
]

export const inputGuarantee = [
    {
        name: "a",
        label: "ยี่ห้อ",
        type: "text",
        placeholder: "a",
        width: "6/12",
        value: "",
    },
    {
        name: "a",
        label: "รุ่น",
        type: "text",
        placeholder: "a",
        width: "6/12",
        value: "",
    },
    {
        name: "a",
        label: "สี",
        type: "text",
        placeholder: "a",
        width: "6/12",
        value: "",
    },
    {
        name: "a",
        label: "ปี คศ.",
        type: "text",
        placeholder: "a",
        width: "6/12",
        value: "",
    },
    {
        name: "a",
        label: "ทะเบียนรถ",
        type: "text",
        placeholder: "a",
        width: "6/12",
        value: "",
    },
    {
        name: "a",
        label: "เลขเครื่องยนต์",
        type: "text",
        placeholder: "a",
        width: "6/12",
        value: "",
    },
    {
        name: "a",
        label: "เลขตัวถัง",
        type: "text",
        placeholder: "a",
        width: "6/12",
        value: "",
    },
    {
        name: "a",
        label: "ราคาขาย",
        type: "text",
        placeholder: "a",
        width: "6/12",
        value: "",
    },
    {
        name: "z",
        label: "เพิ่มเติม",
        type: "text",
        placeholder: "a",
        width: "full",
        value: "",
    },
]