const inputList = [
    {
      name: "a",
      label: "ยี่ห้อรถ",
      type: "select",
      placeholder: "a",
      width: "4/12",
      value: "",
      list: [
        { label: "Toyota", value: "1" },
        { label: "Honda", value: "2" },
        { label: "Suzuki", value: "3" },
        { label: "Isuzu", value: "4" },
      ]
    },
    {
      name: "b",
      label: "รุ่น",
      type: "text",
      placeholder: "b",
      width: "4/12",
      value: "",
      disabled: false,
      requied: true,
    },
    {
      name: "c",
      label: "สี",
      type: "text",
      placeholder: "b",
      width: "4/12",
      value: "",
      disabled: false,
    },
    {
      name: "d",
      label: "ปี",
      type: "text",
      placeholder: "b",
      width: "4/12",
      value: "",
      disabled: false,
    },
    {
        name: "e",
        label: "ทะเบียนรถ",
        type: "text",
        placeholder: "b",
        width: "4/12",
        value: "",
        disabled: false,
      },
      {
        name: "f",
        label: "ชื่อผู้ขาย",
        type: "text",
        placeholder: "b",
        width: "4/12",
        value: "",
        disabled: false,
      },
      {
        name: "g",
        label: "เลขตัวถัง",
        type: "text",
        placeholder: "b",
        width: "4/12",
        value: "",
        disabled: false,
      },
      {
        name: "h",
        label: "เลขเครื่องยนต์",
        type: "text",
        placeholder: "b",
        width: "4/12",
        value: "",
        disabled: false,
      },
      {
        name: "i",
        label: "ราคารับซื้อ",
        type: "text",
        placeholder: "b",
        width: "4/12",
        value: "",
        disabled: false,
      },
      {
        name: "j",
        label: "ค่าซ่อมบำรุง",
        type: "text",
        placeholder: "b",
        width: "4/12",
        value: "",
        disabled: false,
      },
      {
        name: "k",
        label: "ต้นทุน",
        type: "text",
        placeholder: "b",
        width: "4/12",
        value: "",
        disabled: false,
      },
      {
        name: "l",
        label: "กำไรที่ต้องการ",
        type: "text",
        placeholder: "b",
        width: "4/12",
        value: "",
        disabled: false,
      },
      {
        name: "m",
        label: "ราคาขาย",
        type: "text",
        placeholder: "b",
        width: "4/12",
        value: "",
        disabled: false,
      },
      {
        name: "n",
        label: "นายหน้า",
        type: "text",
        placeholder: "b",
        width: "4/12",
        value: "",
        disabled: false,
      },
  ];

  export default inputList