const inputList = [
    {
      name: "carBrand",
      label: "ยี่ห้อรถ",
      type: "select",
      placeholder: "a",
      width: "4/12",
      value: "",
      list: [
        { label: "Toyota", value: "Toyota" },
        { label: "Honda", value: "Honda" },
        { label: "Suzuki", value: "Suzuki" },
        { label: "Isuzu", value: "Isuzu" },
      ],
      requied: true,
    },
    {
      name: "model",
      label: "รุ่น",
      type: "text",
      placeholder: "b",
      width: "4/12",
      value: "",
      disabled: false,
      requied: true,
    },
    {
      name: "carColor",
      label: "สี",
      type: "text",
      placeholder: "b",
      width: "4/12",
      value: "",
      disabled: false,
      requied: true,
    },
    {
      name: "carDate",
      label: "ปี",
      type: "text",
      placeholder: "b",
      width: "4/12",
      value: "",
      disabled: false,
      requied: true,
    },
    {
        name: "licensePlate",
        label: "ทะเบียนรถ",
        type: "text",
        placeholder: "b",
        width: "4/12",
        value: "",
        disabled: false,
        requied: true,
      },
      {
        name: "sellerName",
        label: "ชื่อผู้ขาย",
        type: "text",
        placeholder: "b",
        width: "4/12",
        value: "",
        disabled: false,
        requied: true,
      },
      {
        name: "vin",
        label: "เลขตัวถัง",
        type: "text",
        placeholder: "b",
        width: "4/12",
        value: "",
        disabled: false,
        requied: true,
      },
      {
        name: "engineNumber",
        label: "เลขเครื่องยนต์",
        type: "text",
        placeholder: "b",
        width: "4/12",
        value: "",
        disabled: false,
        requied: true,
      },
      {
        name: "buyingPrice",
        label: "ราคารับซื้อ",
        type: "number",
        placeholder: "b",
        width: "4/12",
        value: "",
        disabled: false,
        requied: true,
      },
      {
        name: "maintenanceCost",
        label: "ค่าซ่อมบำรุง",
        type: "number",
        placeholder: "b",
        width: "4/12",
        value: "",
        disabled: false,
        requied: true,
      },
      {
        name: "cost",
        label: "ต้นทุน",
        type: "number",
        placeholder: "b",
        width: "4/12",
        value: "",
        disabled: false,
        requied: true,
      },
      {
        name: "desiredProfit",
        label: "กำไรที่ต้องการ",
        type: "number",
        placeholder: "b",
        width: "4/12",
        value: "",
        disabled: false,
        requied: true,
      },
      {
        name: "sellingPrice",
        label: "ราคาขาย",
        type: "number",
        placeholder: "b",
        width: "4/12",
        value: "",
        disabled: false,
        requied: true,
      },
      {
        name: "agent",
        label: "นายหน้า",
        type: "text",
        placeholder: "b",
        width: "4/12",
        value: "",
        disabled: false,
        requied: true,
      },
  ];

  export default inputList